version: "3"

services: 

    app:
        build: docker/php
        image: php:7.2-fpm
        volumes:
            - ./:/app
            - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/vhost.conf
        depends_on: 
            - db

    nginx: 
        image: nginx:1.13
        volumes:
            - ./:/app
            - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/vhost.conf
        ports:
            - "80:80"
        depends_on:
            - app

    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: example
            POSTGRES_USER: postgres
            POSTGRES_DB: postgres
        ports: 
            - '5432:5432'

    mailcatcher:
        image: schickling/mailcatcher:latest
        ports:
            - 1080:1080

    adminer:
        image: adminer
        ports: 
            - 8080:8080
        links: 
            - db
