version: "3"

services:

    app:
        container_name: "${APP_NAME}_app"
        build: docker/php
        image: php:7.2-fpm
        volumes:
            - ./:/app
            - ./docker/nginx/templates:/etc/nginx/templates
        depends_on:
            - db

    nginx:
        container_name: "${APP_NAME}_nginx"
        image: nginx:1.19
        environment:
            - SERVER_NAME=${APP_URL}
        volumes:
            - ./:/app
            - ./docker/nginx/templates:/etc/nginx/templates
        ports:
            - "80:80"
        depends_on:
            - app

    db:
        container_name: "${APP_NAME}_db"
        image: postgres
        restart: always
        volumes:
            - ./docker/postgres/data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_DB: ${DB_DATABASE}
        ports:
            - '5432:5432'

    mailcatcher:
        container_name: "${APP_NAME}_mailcatcher"
        image: schickling/mailcatcher:latest
        ports:
            - 1080:1080

    adminer:
        container_name: "${APP_NAME}_adminer"
        image: adminer
        ports:
            - 8080:8080
        links:
            - db

#    sphinx:
#      container_name: "${APP_NAME}_sphinx"
#      image: macbre/sphinxsearch:3.2.1
##      command: indexer --rotate --all
#      ports:
#        - "127.0.0.1:36307:36307"
#      volumes:
#        - ./docker/sphinx/data:/opt/sphinx/index
#        - ./docker/sphinx/sphinx.conf:/opt/sphinx/conf/sphinx.conf
#      env_file:
#        - .env
#      links:
#        - db
#      depends_on:
#        - db
