version: "3"

services: 

    app:
        container_name: "${APP_NAME}_app"
        build: docker/php
        image: php:7.2-fpm
        volumes:
            - ./:/app
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/vhost.conf
        depends_on: 
            - db

    nginx: 
        container_name: "${APP_NAME}_nginx"
        image: nginx:1.13
        environment: 
            - SERVER_NAME=${APP_URL}
        volumes:
            - ./:/app
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf.txt
        ports:
            - "80:80"
        command: /bin/bash -c "envsubst '$$SERVER_NAME' < /etc/nginx/conf.d/nginx.conf.txt > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'" 
        depends_on:
            - app

    db:
        container_name: "${APP_NAME}_db"
        image: postgres
        restart: always
        volumes: 
            - ./docker/postgres/data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: example
            POSTGRES_USER: postgres
            POSTGRES_DB: postgres
        ports: 
            - '5432:5432'

    mailcatcher:
        container_name: "${APP_NAME}_mailcatcher"
        image: schickling/mailcatcher:latest
        ports:
            - 1080:1080

    adminer:
        container_name: "${APP_NAME}_adminer"
        image: adminer
        ports: 
            - 8080:8080
        links: 
            - db
